name: Build and Push (SLIM)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push slim image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ksarpdev/example-22:slim,ksarpdev/example-22:slim-${{ github.sha }}